export const CURATOR_COPY = {
	brand: { en: "OmniMind Web Access", "zh-CN": "OmniMind 网络访问" },
	all: { en: "All", "zh-CN": "全部" },
	clickToAdjust: { en: "Click to adjust", "zh-CN": "点击调整" },
	secondsShort: { en: "sec", "zh-CN": "秒" },
	set: { en: "Set", "zh-CN": "设置" },
	searching: { en: "Searching", "zh-CN": "正在搜索" },
	searchingEllipsis: { en: "Searching…", "zh-CN": "正在搜索…" },
	resultsAppear: { en: "Results will appear below as they complete.", "zh-CN": "搜索完成后，结果会依次显示在下方。" },
	observerResultsAppear: { en: "Live results are shown here while the agent continues automatically.", "zh-CN": "搜索结果会实时显示在这里，Agent 将自动继续。" },
	observerDisplaying: { en: "Showing the live search process in OmniMind Browser. The agent will continue automatically.", "zh-CN": "正在 OmniMind 浏览器中显示实时搜索过程，Agent 将自动继续。" },
	observerDisplayFailed: { en: "Search is continuing, but OmniMind could not display the live search process.", "zh-CN": "搜索仍在继续，但 OmniMind 无法显示实时搜索过程。" },
	observerSummarySent: { en: "Summary sent to the agent. The run is continuing.", "zh-CN": "摘要已发送给 Agent，任务正在继续。" },
	observerResultsSent: { en: "Results sent to the agent. The run is continuing.", "zh-CN": "结果已发送给 Agent，任务正在继续。" },
	providerPersistedAndResearched: { en: "Set {provider} as the default and searched the current results again.", "zh-CN": "已将 {provider} 设为默认，并重新搜索当前结果。" },
	sendRaw: { en: "Send selected results without summary", "zh-CN": "直接发送所选结果，不生成摘要" },
	addSearch: { en: "Add a search…", "zh-CN": "添加搜索…" },
	rewriteQuery: { en: "Rewrite query with AI", "zh-CN": "用 AI 改写查询" },
	summaryReview: { en: "Summary review", "zh-CN": "摘要审查" },
	reviewSummaryDraft: { en: "Review summary draft", "zh-CN": "审查摘要草稿" },
	editSummary: { en: "Edit the summary before approving.", "zh-CN": "批准前可继续编辑摘要。" },
	summaryProvider: { en: "Summary provider", "zh-CN": "摘要服务" },
	summaryModel: { en: "Summary model", "zh-CN": "摘要模型" },
	generatingSummaryDraft: { en: "Generating summary draft…", "zh-CN": "正在生成摘要草稿…" },
	summaryDraftPlaceholder: { en: "Summary draft will appear here…", "zh-CN": "摘要草稿将在这里显示…" },
	optionalFeedback: { en: "Optional feedback for regeneration…", "zh-CN": "可选：填写重新生成摘要的反馈…" },
	back: { en: "Back", "zh-CN": "返回" },
	regenerate: { en: "Regenerate", "zh-CN": "重新生成" },
	previewRenderedSummary: { en: "Preview rendered summary", "zh-CN": "预览渲染后的摘要" },
	preview: { en: "Preview", "zh-CN": "预览" },
	approve: { en: "Approve", "zh-CN": "批准" },
	toggleAll: { en: "Toggle all", "zh-CN": "切换全选" },
	generate: { en: "Generate", "zh-CN": "生成" },
	cancel: { en: "Cancel", "zh-CN": "取消" },
	waitingResults: { en: "Waiting for results…", "zh-CN": "正在等待搜索结果…" },
	resultsSent: { en: "Results sent", "zh-CN": "结果已发送" },
	sessionEnded: { en: "Session Ended", "zh-CN": "本次审查已结束" },
	timeoutAllResults: { en: "Time’s up — sending all results to your agent.", "zh-CN": "审查已超时，正在将全部结果发送给 Agent。" },
	closingIn: { en: "Closing in", "zh-CN": "将在" },
	closingUnitSuffix: { en: "s", "zh-CN": " 秒后关闭" },
	summaryPreview: { en: "Summary Preview", "zh-CN": "摘要预览" },
	close: { en: "Close", "zh-CN": "关闭" },
	feedback: { en: "Feedback…", "zh-CN": "反馈…" },
	auto: { en: "Auto", "zh-CN": "自动" },
	invalidJsonResponsePrefix: { en: "Invalid JSON response from ", "zh-CN": "响应不是有效 JSON：" },
	checkResults: { en: "Check the results to include, then generate and approve a summary.", "zh-CN": "勾选要采用的结果，然后生成并批准摘要。" },
	waitingRemainingSearches: { en: "Waiting for remaining searches…", "zh-CN": "正在等待其余搜索完成…" },
	planningSummary: { en: "Planning summary", "zh-CN": "正在规划摘要" },
	draftingSummary: { en: "Drafting summary", "zh-CN": "正在撰写摘要" },
	polishingSummary: { en: "Polishing summary", "zh-CN": "正在完善摘要" },
	selectionChangedRegenerating: { en: "Selection changed — regenerating summary…", "zh-CN": "所选来源已变化，正在重新生成摘要…" },
	selectionChangedSoon: { en: "Selection changed — summary will regenerate shortly…", "zh-CN": "所选来源已变化，摘要即将重新生成…" },
	generatingSummary: { en: "Generating summary…", "zh-CN": "正在生成摘要…" },
	summaryReady: { en: "Summary ready", "zh-CN": "摘要已就绪" },
	noResultsYet: { en: "No results yet", "zh-CN": "暂无结果" },
	generateSummary: { en: "Generate summary", "zh-CN": "生成摘要" },
	selectResultsToSummarize: { en: "Select results to summarize", "zh-CN": "请选择要总结的结果" },
	searchingSources: { en: "Searching sources", "zh-CN": "正在搜索来源" },
	failed: { en: "Failed", "zh-CN": "失败" },
	searchFailed: { en: "Search failed", "zh-CN": "搜索失败" },
	sources: { en: "Sources", "zh-CN": "来源" },
	failedToSaveProviderPrefix: { en: "Failed to save provider preference: ", "zh-CN": "保存搜索服务偏好失败：" },
	unknownError: { en: "unknown error", "zh-CN": "未知错误" },
	researchFailedPrefix: { en: "Re-search failed: ", "zh-CN": "重新搜索失败：" },
	rewriteFailedPrefix: { en: "Rewrite failed: ", "zh-CN": "改写查询失败：" },
	addSearchFailedPrefix: { en: "Failed to add search: ", "zh-CN": "添加搜索失败：" },
	submitInProgress: { en: "Submit already in progress", "zh-CN": "正在提交，请稍候" },
	timeoutCurrentSummary: { en: "Time’s up — submitting current summary state.", "zh-CN": "审查已超时，正在提交当前摘要状态。" },
	whatDoYouNeed: { en: "What do you need?", "zh-CN": "你需要查找什么？" },
	searchAnything: { en: "Search for anything below, then generate and approve a summary.", "zh-CN": "在下方搜索所需内容，然后生成并批准摘要。" },
	invalidLiveEventPrefix: { en: "Invalid live event payload: ", "zh-CN": "实时事件数据无效：" },
	unknownParseError: { en: "unknown parse error", "zh-CN": "未知解析错误" },
	liveDisconnectedPolling: { en: "Live search updates disconnected. Reconnecting and polling for results.", "zh-CN": "实时搜索更新已断开，正在重连并轮询结果。" },
	liveDisconnectedRetryPrefix: { en: "Live search updates disconnected. Retrying: ", "zh-CN": "实时搜索更新已断开，正在重试：" },
	selectOneToSummarize: { en: "Select at least one result to summarize", "zh-CN": "请至少选择一项结果以生成摘要" },
	waitForSearches: { en: "Wait for running searches to finish before generating summary", "zh-CN": "请等待正在进行的搜索完成后再生成摘要" },
	summaryResponseEmpty: { en: "Summary response was empty", "zh-CN": "摘要响应为空" },
	generateSummaryFailedPrefix: { en: "Failed to generate summary — ", "zh-CN": "生成摘要失败：" },
	selectOneBeforeApprove: { en: "Select at least one result before approving", "zh-CN": "批准前请至少选择一项结果" },
	approveFailedPrefix: { en: "Failed to approve summary — ", "zh-CN": "批准摘要失败：" },
	agentMovedOn: { en: "the agent may have moved on", "zh-CN": "Agent 可能已继续执行" },
	skipped: { en: "Skipped", "zh-CN": "已跳过" },
	cancelFailedPrefix: { en: "Failed to cancel — ", "zh-CN": "取消失败：" },
	sendResultsFailedPrefix: { en: "Failed to send results — ", "zh-CN": "发送结果失败：" },
	searchesCompleteProgress: { en: "{completed} of {total} Searches Complete", "zh-CN": "已完成 {completed}/{total} 个搜索" },
	searchesCompleteOne: { en: "{completed} Search Complete", "zh-CN": "已完成 {completed} 个搜索" },
	searchesCompleteMany: { en: "{completed} Searches Complete", "zh-CN": "已完成 {completed} 个搜索" },
	completedStatus: { en: "{completed} completed", "zh-CN": "已完成 {completed}" },
	completedSearchingStatus: { en: "{completed} completed, {searching} searching", "zh-CN": "已完成 {completed}，搜索中 {searching}" },
	phaseWithModel: { en: "{phase} with {model}…", "zh-CN": "{phase} · {model}…" },
	selectedOne: { en: "{count} selected result", "zh-CN": "已选择 {count} 项结果" },
	selectedMany: { en: "{count} selected results", "zh-CN": "已选择 {count} 项结果" },
	summarizingWithModel: { en: "Summarizing {selection} with {model}…", "zh-CN": "正在使用 {model} 总结{selection}…" },
	summarizingSelection: { en: "Summarizing {selection}…", "zh-CN": "正在总结{selection}…" },
	deterministicFallbackSummary: { en: "Deterministic fallback summary", "zh-CN": "确定性备用摘要" },
	fallbackSummary: { en: "Fallback summary", "zh-CN": "备用摘要" },
	fallbackReason: { en: " Reason: {reason}.", "zh-CN": " 原因：{reason}。" },
	fallbackSelection: { en: "{label} of {selection}.{reason}", "zh-CN": "{label}（{selection}）。{reason}" },
	summaryOfSelection: { en: "Summary of {selection}. Edit directly, regenerate with feedback, or approve.", "zh-CN": "{selection}的摘要。可直接编辑、根据反馈重新生成或批准。" },
	searchingQuery: { en: "Searching {done}/{total} query…", "zh-CN": "正在搜索 {done}/{total}…" },
	searchingQueries: { en: "Searching {done}/{total} queries…", "zh-CN": "正在搜索 {done}/{total}…" },
	sourceCountOne: { en: "{count} source", "zh-CN": "{count} 个来源" },
	sourceCountMany: { en: "{count} sources", "zh-CN": "{count} 个来源" },
	alsoTry: { en: "Also try", "zh-CN": "也可尝试" },
} as const;

export type CuratorCopy = {
	readonly [Key in keyof typeof CURATOR_COPY]: string;
};

export function resolveCuratorCopy(locale: "en" | "zh-CN"): CuratorCopy {
	return Object.fromEntries(
		Object.entries(CURATOR_COPY).map(([key, value]) => [key, value[locale]]),
	) as CuratorCopy;
}
